### ISSUE TITLE
worker_groups error while aws provision

### ISSUE THREAD

**Issue by ganapathichidambaram** [Viking-VoIP/full-voip-on-k8s#1]
Hi,
Trying to create EKS using this repo as it as but throws some error on worker_group creation.

Where additionally there are some error on subnets and s3 acl, where i corrected those to come into this stage of error.

```

 Error: Unsupported argument
│ 
│   on ../../modules/eks/main.tf line 22, in module "eks":
│   22:   worker_groups = [
│ 
│ An argument named "worker_groups" is not expected here.
╵
make[1]: *** [Makefile:16: apply] Error 1
```

**Comment by davidcsi** [comment]
This could be related to the kubernetes version. I'll test and let you know.

**Comment by ganapathichidambaram** [comment]
Adding version         = "17.24.0" on eks module resolving this error

**Comment by ganapathichidambaram** [comment]
I just curious to know that why there is no service definition files are added. RTP ports are all opened/exposed and it's working on kubernetes ?. while exporting huge port range then docker proxy will crash, where same here as well ?.

is it production ready ?

**Comment by davidcsi** [comment]
this is a WIP. Also ports are not opened individually, FS runs in network mode.
